name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy pytest-cov mutmut
      - name: Lint
        run: |
          black --check core agents labs tools tests
          flake8 core agents labs tools tests
      - name: Type Check
        run: mypy core agents labs tools
      - name: Test with coverage
        run: pytest --cov=.
      - name: Mutation tests
        run: mutmut run --paths-to-mutate core --runner pytest --tests-dir tests --use-coverage
      - name: Docker build
        run: docker build -t eidos-brain .
